logo: Home
title: Divya Shan Photography
description: > 
  An experiment with both photography and code. 
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://divya-ms.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Divya Shan Photography # add banner title
banner-desc: Bringing together my passions for both photography and coding. 

# Author settings
author-pic: face.jpg # your photo
author-name: Divya Shan
about-author: Attends UVA. 
email: dms5pc@virginia.edu 
phone: (703)-832-1070 

# Social link
instagram_url: https://www.instagram.com/divyashan_/
facebook_url: https://www.facebook.com/profile.php?id=100006395430393

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
