title: Divya Shan Photography
description: > 
  An experiment with both photography and code. 
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://divya-ms.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Divya Shan Photography # add banner title
banner-desc: Bringing together my passions for both photography and coding. 

# Author settings
author-pic: face.jpg # your photo
author-name: Divya Shan
about-author: My life motto is to make the most out of every opportunity I get. Through photography, I hope to challenge myself to use even the most simple and ordinary backgrounds to create unique and interesting photos. Ultimately, I want to meet new people and make sure they have a great time during the shoot. If you're interested, go ahead and e-mail me!</p>
email: email@virginia.edu 
phone: (703)-703-703 

# Social link
instagram_url: https://www.instagram.com/
facebook_url: https://www.facebook.com/

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
